require "plugins.packer-downloads"
require "plugins.tmux-navigator"
require "plugins.nvim-tree"
require "plugins.treesitter"
require "plugins.toggleterm"
require "plugins.cmp"
require "plugins.lualine"
