require "plugins.lazy" -- This is where lazy gets all plugins, should be at the top
require "plugins.comment"
require "plugins.leap"
require "plugins.nvim-tree"
require "plugins.treesitter"
-- require "plugins.toggleterm"
require "plugins.cmp"
require "plugins.lualine"
require "plugins.telescope"
require "plugins.gitsigns"
